### ISSUE TITLE
CLI Control

### ISSUE THREAD

**Issue by ajw287** [ajw287/diffgerber#3]
Comments at KiCON has shown that the integration in to CI/CD process' requires that the code can be run from the CLI.  The plan here is to add arguments that switch to 'quiet' operation and output images etc.

**Comment by ajw287** [comment]
Basic CLI added in diffgerber-cli.py.  Can be used to generate cute icon outputs:

`python diffgerber-cli.py ../examples/pcb-1-a ../examples/pcb-1-b/ out 100`

**Comment by ajw287** [comment]
the cli has a '-h/--help' option.  I'm going to add a 'quiet mode' that suppresses command line output.  Any other options?

**Comment by Argmaster** [comment]
You are doing CLI fully manually, maybe it would be more effective to use [`click`](https://pypi.org/project/click/) or at least [`argparse`](https://docs.python.org/3/library/argparse.html).

**Comment by ajw287** [comment]
Thanks for this - sometimes knowing the right library is half the battle!
